apiVersion: v1
kind: Service
metadata:
  name: welcome-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: welcome-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - image: kwangko/test1:12
          imagePullPolicy: IfNotPresent
          name: cicd-web-project
          ports:
            - containerPort: 8080
              protocol: TCP
#      imagePullSecrets:
#        - name: regcred


# Docker hub 에서 private 이미지 가져올 경우
#kubectl create secret docker-registry regcred \
#  --docker-server=https://index.docker.io/v1/ \
#  --docker-username=<도커허브 계정아이디> \
#  --docker-password=<도커허브 비밀번호> \
#  --docker-email=<도커허브 가입 이메일> \
#  --namespace=<네임스페이스>

# Docker hub 이 아닌 다른 Registry 를 사용할경우
#kubectl create secret docker-registry regcred \
#  --docker-server=192.168.0.33 \
#  --docker-username=<사용자명> \
#  --docker-password=<비밀번호> \
#  --docker-email=<이메일> \



